#!/usr/local/bin/python3
# -*- coding:utf-8 -*-
import argparse
import subprocess
import os
import platform
import sys

def build(build_dir, source_dir):
    cmd = []
    cmd.extend(["g++", "-std=c++14", "-g", "-Wall",
                "-I/usr/local/include",
                "-L/usr/local/lib"])
    
    _platform = platform.system()

    # Linker flags
    if _platform == "Linux":
        cmd.extend(["-lopengl", "-lglfw", "-lglew"])
        
    elif _platform == "Darwin":
        cmd.extend(["-framework","OpenGL","-lglfw","-lglew"])
    else:
        print(_platform + " not supported")
        sys.exit()

    cmd.extend(["-o", build_dir+"/main",
                 source_dir+"/main.cpp"])

    subprocess.call(cmd)


def run(build_dir):
    subprocess.call([build_dir+"/main"])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-b", "--build", help="build only", action="store_true")
    parser.add_argument("-r", "--run", help="run only", action="store_true")
    argv = parser.parse_args()

    build_dir = "./build"
    source_dir = "./src"

    if argv.build:
        build(build_dir, source_dir)
    elif argv.run:
        run(build_dir)
    else:
        build(build_dir, source_dir)
        run(build_dir)
